#!/bin/sh

# This is my script for setting up ubuntu machines in
# a similar setup to how thoughtbot's laptop script
# works (https://github.com/thoughtbot/laptop)

append_to_zshrc() {
  if [ -w "$HOME/.zshrc.local" ]; then
    zshrc="$HOME/.zshrc.local"
  else
    zshrc="$HOME/.zshrc"
  fi

  grep -q -F "$1" "$zshrc" || echo "$1" >> "$zshrc"
}

set -e

[ ! -e "$HOME/.bin" ] && mkdir "$HOME/.bin"
[ ! -f "$HOME/.zshrc" ] && touch "$HOME/.zshrc"

append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'

# add all ppa's first
sudo add-apt-repository -y "deb https://cli-assets.heroku.com/branches/stable/apt ./"
curl -L https://cli-assets.heroku.com/apt/release.key | sudo apt-key add -
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

# basics
sudo apt-get install ctags git openssl tmux vim zsh wget
chsh -s "$(which zsh)"

# heroku
sudo apt-get install heroku

# github
# TODO: add hub compilation and copy to ~/.bin
# sudo apt-get install hub

# image manip
sudo apt-get install imagemagick --fix-missing

# capybara-webkit dependencies
sudo apt-get install qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x

# language related
[ ! -e "$HOME/.rbenv" ] && git clone https://github.com/rbenv/rbenv.git ~/.rbenv
cd ~/.rbenv && src/configure && make -C src
sudo apt-get install -y nodejs

# databases
sudo apt-get install redis-server
sudo apt-get install postgresql postgresql-contrib

find_latest_ruby() {
  rbenv install -l | grep -v - | tail -1 | sed -e 's/^ *//'
}
ruby_version="$(find_latest_ruby)"

# rbenv setup
append_to_zshrc 'export PATH="$HOME/.rbenv/bin:$PATH"'
append_to_zshrc 'eval "$(rbenv init - --no-rehash)"'

eval "$(rbenv init -)"
rbenv install -s "$ruby_version"

if ! rbenv versions | grep -Fq "$ruby_version"; then
  rbenv install -s "$ruby_version"
fi

rbenv global "$ruby_version"
rbenv shell "$ruby_version"

gem update --system
gem install bundler
gem install parity
